version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nms-server
    ports:
      - "5175:3000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: nms-admin
    ports:
      - "5174:5173"
    environment:
      - ENV=production

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nms-client
    ports:
      - "5173:5173"
    environment:
      - ENV=production

networks:
  default:
    name: pws_frontend_default
    external: true
